language: go

go:
  - "1.13.x"
env:
  global:
    GO111MODULE=off

before_install:
  - go get -u github.com/mattn/goveralls
  - go get github.com/n-is/gopher-lua
  - go get github.com/n-is/tengo
script:
  # - cd lua; go build -v .; cd ..
  # - cd tengo; go build -v .; cd ..
  - go test -v ./...
  - $GOPATH/bin/goveralls -service=travis-ci