name: Go
on: [push]
jobs:

  build_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get github.com/n-is/goEmbed/...
        go get -v -t -d ./...

    - name: Build Package
      run: |
        go build -v ./...

    - name: Run Unit tests
      run: |
        go test -v ./...

    # - name: Send coverage
    #   env:
    #     COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: |
    #     GO111MODULE=off go get github.com/mattn/goveralls
    #     ls
    #     cat "profile.cov"
    #     echo $(go env GOPATH)
    #     $(go env GOPATH)/bin/goveralls -coverprofile="profile.cov" -service="Github Action"
